services:
    # app.product:
    #     class: App\Controller\ProductController
    #     calls:
    #         - [setContainer, ['@service_container']]

    app.service.product:
        class: App\Services\ProductService
        arguments:
            - '@service_container'

    app.service.user:
        class: App\Services\UserService
        arguments:
            - '@service_container'

    app.service.productuser:
        class: App\Services\ProductUserService
        arguments:
            - '@service_container'

    app.token_authenticator:
        class: App\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager']
