services:
    # app.product:
    #     class: App\Controller\ProductController
    #     calls:
    #         - [setContainer, ['@service_container']]

    app.service.product:
        class: App\Services\ProductService
        calls:
            - [setContainer, ['@service_container']]

    app.service.user:
        class: App\Services\UserService
        calls:
            - [setContainer, ['@service_container']]
            - [init, ['%secret%']]

    app.service.productuser:
        class: App\Services\ProductUserService
        calls:
            - [setContainer, ['@service_container']]
            - [init, []]

    app.token_authenticator:
        class: App\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager']
