services:
    # app.product:
    #     class: App\Controller\ProductController
    #     calls:
    #         - [setContainer, ['@service_container']]

    app.service.product:
        class: App\Services\ProductService
        arguments:
          - '@form.factory'
          - '@doctrine'

    app.service.user:
        class: App\Services\UserService
        arguments:
          - '@form.factory'
          - '@doctrine'
          - '%secret%'

    app.service.productuser:
        class: App\Services\ProductUserService
        arguments :
          - '@form.factory'
          - '@doctrine'
          - '@security.token_storage'

    app.token_authenticator:
        class: App\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager']
